/* eslint-disable */
/**
 * This file was automatically generated by pydantic2ts.
 * Do not modify it by hand. Instead, regenerate it with:
 *
 *   task generate-types
 *
 * Source: backend/api/schema.py
 */

export interface GroupPredictionInformationResponse {
	total: number;
	hiredAndCompetent: number;
	hiredButNotCompetent: number;
	notHiredButCompetent: number;
	notHiredAndNotCompetent: number;
	hired: number;
	hiredRate: number;
	notHired: number;
	notHiredRate: number;
	correct: number;
	correctRate: number;
	incorrect: number;
	incorrectRate: number;
	competent: number;
	competentRate: number;
	notCompetent: number;
	notCompetentRate: number;
	accuracy: number;
	falseNegativeRate: number;
	falsePositiveRate: number;
	falseDiscoveryRate: number;
	falseOmissionRate: number;
}

export interface RecruiterBiasAnalysisResponse {
	general: GroupPredictionInformationResponse;
	byGroup: Record<string, GroupPredictionInformationResponse>;
}

export interface CharacteristicResponse {
	name: string;
	type: 'categorical';
	categoryNames: string[];
	priorDistribution?: number[] | null;
}

export interface NetworkResponse {
	graph?: null;
	scoreCharacteristic: string;
	applicationCharacteristics: string[];
	characteristics: Record<string, CharacteristicResponse>;
	predefined: boolean;
}
